### PR TITLE
Switch to using a config json file to get URLs, tokens, and workspace…

### PR DESCRIPTION
**Pull request by laurahlark**
… projects. Also adds a test config for the tests to use. An encrypted version has already been uploaded to Travis. This should allow us to run integration tests from Travis.

### CODE REVIEW

**Comment by laurahlark** [comment]
Feel free to discuss config file. It's the same deal as the tokens file, except that it pulls a default config file from the adam folder. Changed auth_demo to config_demo since that's really what it's for. Updates all demos to use config (which also gets rid of mentions of catch-all project, I believe). Also renamed authorization to authentication everywhere since it's doing authentication, not authorization. This also packages up a test tokens file for Travis - the encrypted version is checked in, the unencrypted version is on my computer.

I'll chat the uw team to let them know before I submit.

**Comment by AstrogatorJohn** [comment]
LFTM; I like that there are several environments... (dev, prod) so that will help a lot.

So, the test can run with an encypted token?

**Comment by laurahlark** [comment]
To see the projects you have access to, you should be able to go to

http://pro-equinox-162418.appspot.com/_ah/api/adam/v1/project?token=<your token here>

To see the runs in a project, you should be able to go to

http://pro-equinox-162418.appspot.com/_ah/api/adam/v1/batch?token=<your token here>&project_uuid=<project to look under>

Are these working for you?

**Comment by laurahlark** [comment]
@AstrogatorJohn I think what happens is that the test runner will decrypt the file and put it in with the tests when it runs them. I need to confirm, but I'll do that next when (hopefully) I move the integration tests over.

**Comment by laurahlark** [comment]
resolves #7
also has to do with #8

**Comment by samotiwala** [comment]
@laurahlark yeah those work, but it's starting to get a little confusing. Can we add some sort of documentation (either in the readme or elsewhere with a link in the readme) for how this works and how to access runs (like you mentioned above)? There might also be some terminology mixup/confusion. For example, 'workspace' and 'project' or 'project_uuid' look interchangeable? And what if you get read access to someone else's projects? Can you have more than one project? How? Maybe it's just me having a hard time keeping up, but I think some kind of doc would help. 🙃

**Pull request merged**
