### PR TITLE
Fix lint errors for adam/ and adam/tests

### PR DESCRIPTION
**Pull request by laurahlark**
Using 

autopep8 --in-place --recursive --max-line-length=100 <files>

and

flake8 <files>

### CODE REVIEW

**Comment by laurahlark** [comment]
#16

**Comment by laurahlark** [comment]
Now command to lint should just be flake8. Note: I plan on ignoring the coveralls warning, since it's just due to some uncovered lines getting split up.

**Comment by samotiwala** [comment]
Do you know what this coverage decreased check means?

**Comment by laurahlark** [comment]
Yeah, I’m pretty sure it’s just that there are some lines that were already uncovered that were split into multiple lines by this change, so there appears to be coverage loss (since I’m pretty sure coverage is just lines covered / total lines). So no logical change in coverage, since the same code is uncovered, but more lines uncovered.

**Comment by laurahlark** [comment]
Merging, and ignoring slight coverage decrease due to uncovered lines being split into multiple lines.

**Pull request merged**
